services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - 1883:1883
    networks:
      - influxdb_network
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro  # Read-only config file
      - mosquitto_data:/mosquitto/data  # Persistent data volume
      - mosquitto_log:/mosquitto/log  # Persistent log volume
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
      # Optional: Mount a custom InfluxDB configuration file
      - influxdb_config:/etc/influxdb2:rw
    env_file:
      - influxdb.env
    networks:
      - influxdb_network
    restart: unless-stopped

  telegraf:
    image: telegraf:1.29.5-alpine
    container_name: telegraf
    ports:
      - 8125:8125
    volumes:
      # Mount your Telegraf configuration file (replace with your path)
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influxdb_network
    restart: unless-stopped
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:10.2.4
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    env_file:
    - grafana.env
    networks:
      - influxdb_network
    restart: unless-stopped
    depends_on:
      - influxdb


networks:
  influxdb_network:

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  influxdb_config:
  grafana_storage: