version: "3.9"

services:
  influxdb:
    image: telegraf:1.29.5-alpine
    container_name: telegraf
    ports:
      - 8125:8125
    volumes:
      # Mount your Telegraf configuration file (replace with your path)
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - telegraf_network
    restart: unless-stopped

networks:
  telegraf_network: