version: "3.9"

services:
  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb2:rw
      # Optional: Mount a custom InfluxDB configuration file
      - ./config:/etc/influxdb2:rw
    env_file:
      - .env
    networks:
      - influxdb_network
    restart: unless-stopped

networks:
  influxdb_network: