version: "3.9"

services:
  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb2:rw
      # Optional: Mount a custom InfluxDB configuration file
      - ./config:/etc/influxdb2:rw
    env_file:
      - influxdb.env
    networks:
      - influxdb_network
    restart: unless-stopped

  telegraf:
    image: telegraf:1.29.5-alpine
    container_name: telegraf
    ports:
      - 8125:8125
    volumes:
      # Mount your Telegraf configuration file (replace with your path)
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influxdb_network
    restart: unless-stopped
    depends_on:
      - influxdb

networks:
  influxdb_network: